-- MySQL Script generated by MySQL Workbench
-- Tue Mar 14 21:21:29 2023
-- Model: New Model    Version: 1.0.0
-- MySQL Workbench Forward Engineering





-- -----------------------------------------------------
-- Table `film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS film (
  idfilm INT NOT NULL,
  title VARCHAR(100) NULL,
  IMG VARCHAR(45) NULL,
  description LONGTEXT NULL,
  link VARCHAR(100) NULL,
  PRIMARY KEY (idfilm),
  UNIQUE INDEX title_UNIQUE (title ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Ticket (
  idTicket INT NOT NULL AUTO_INCREMENT,
  film_idfilm INT NOT NULL,
  Client_idClient INT NOT NULL,
  PRIMARY KEY (idTicket),
  CONSTRAINT fk_Ticket_film1
    FOREIGN KEY (film_idfilm)
    REFERENCES film (idfilm)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Ticket1_Client
    FOREIGN KEY (Client_idClient)
    REFERENCES Cclient (idclient)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cclient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Cclient (
  idclient INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(45) NULL,
  adresse VARCHAR(50) NULL,
  mdp VARCHAR(100) NOT NULL,
  phone VARCHAR(15) NOT NULL,
  PRIMARY KEY (idClient)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Agent (
  idAgent INT NOT NULL,
  agentlogin VARCHAR(45) NULL,
  agentMDP VARCHAR(45) NULL,
  PRIMARY KEY (idAgent))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS salle (
  idsalle INT NOT NULL,
  capacité INT NOT NULL,
  PRIMARY KEY (idsalle))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plannifier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS plannifier (
  film_idfilm INT NOT NULL,
  Agent_idAgent INT NOT NULL,
  dateP DATE NULL,
  heure TIME NULL,
  salle_idsalle INT NOT NULL,
  id_plan INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id_plan),
  CONSTRAINT fk_film
    FOREIGN KEY (film_idfilm)
    REFERENCES film (idfilm)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Agent
    FOREIGN KEY (Agent_idAgent)
    REFERENCES Agent (idAgent)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_salle
    FOREIGN KEY (salle_idsalle)
    REFERENCES salle(idsalle)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `film`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO film(`idfilm`, `title`, `IMG`, `description`, `link`) VALUES (123, 'pirates of the carribean:at worlds end', 'pirates.jpg', 'as jack sparrow and his crew find a new journey in the seven seas,davy jones  looming threat is upahead,as the world is facing it doom.will captain sparrow find a way to end it somehow?', 'https://www.youtube.com/watch?v=HKSZtp_OGHY');
INSERT INTO film (`idfilm`, `title`, `IMG`, `description`, `link`) VALUES (789, 'howls moving castle', 'howl.jpg', '"here is my heart,please keep it safe\",such a romantic thing to say right?but what if you saw that case litteraly?dive with ghibli studio into this iconic story and see for yourself!', 'https://www.youtube.com/watch?v=iwROgK94zcM');
INSERT INTO film (`idfilm`, `title`, `IMG`, `description`, `link`) VALUES (001, 'deadpool', 'deadpool.jfif', 'rated +18,but with it humour,deadpool delivers a lot in the entirety of its time,packed with top notch action:this movie is simply a package you dont want to miss!', 'https://www.youtube.com/watch?v=ONHBaC-pfsk');
INSERT INTO film (`idfilm`, `title`, `IMG`, `description`, `link`) VALUES (005, 'Assassins creed the movie', 'creed.jpg', 'the dream of gamers worldwide has become a reality,for this franchise have long since needed its own movie.new to the title?you wont even feel as a stranger!dive in the world of assassins creed and experience an action movie like none other,involving two ancient orders who have been battling through history', 'https://www.youtube.com/watch?v=4haJD6W136c');
INSERT INTO film(`idfilm`, `title`, `IMG`, `description`, `link`) VALUES (004, 'Moana', 'moana.jpg', 'look no further ladies and gents,if you want a family you can watch with family while having the utmost fun:then this is your pick.one of disnets best animated films by far,putting the magic of huwai in an existing adventurous story', 'https://www.youtube.com/watch?v=LKFuXETZUsI');

COMMIT;

-- -----------------------------------------------------
-- Data for table `Agent`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO Agent (`idAgent`, `agentlogin`, `agentMDP`) VALUES (8426, 'WORKER1.0', '21471006');
INSERT INTO Agent (`idAgent`, `agentlogin`, `agentMDP`) VALUES (7913, 'WORKER2.0', '00658941');
INSERT INTO Agent (`idAgent`, `agentlogin`, `agentMDP`) VALUES (9435, 'WORKER3.0', '89454233');

COMMIT;


-- -----------------------------------------------------
-- Data for table `salle`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO salle(`idsalle`, `capacité`) VALUES (01, 49);
INSERT INTO salle(`idsalle`, `capacité`) VALUES (02, 45);
INSERT INTO salle (`idsalle`, `capacité`) VALUES (03, 48);

COMMIT;